PackageIdentifier: Typsastra.Typsastra
PackageVersion: 0.9.1
Platform: Windows.Latest
InstallerType: wix
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Sovichea/typsastra/releases/download/v0.9.1/Typsastra_0.9.1_x64_en-US.msi
    InstallerSha256: 3f6f959f6dac2fba3933e1ff045f99496c50716e8095069841ee8922b958b14b
    ProductCode: '{9EE6BED8-BE0F-490E-8E49-80994ED972B9}'
    UpgradeCode: '{552C8F47-DD8F-586E-B36F-B23E2CEC2A14}'
  - Architecture: arm64
    InstallerUrl: https://github.com/Sovichea/typsastra/releases/download/v0.9.1/Typsastra_0.9.1_arm64_en-US.msi
    InstallerSha256: 969e6cad71f01e1f5078899084669b05524d7eeb287b363654f6602f374e890d
    ProductCode: '{F0726CCE-9ACF-475E-93FA-0E11D8E49E31}'
    UpgradeCode: '{552C8F47-DD8F-586E-B36F-B23E2CEC2A14}'
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
ElevationRequirement: elevationRequired
ReleaseDate: 2026-10-03
ManifestType: installer
ManifestVersion: 1.12.0